name: files editor action test

# on:
#   schedule:
#     - cron:  '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Files Editor Action Test
        uses: guangzhengli/files-editor-action@main
        with:
          file_name: 'members.txt'
          type: 'sort'